New upstream version 3.5.3

diff --git a/mlocal/frags/Makefile.stub b/mlocal/frags/Makefile.stub
--- a/mlocal/frags/Makefile.stub
+++ b/mlocal/frags/Makefile.stub
@@ -1,7 +1,8 @@
 all: $(ALL)
 
 .PHONY: man
-man:
+man: singularity
+	mkdir -p $(DESTDIR)$(MANDIR)/man1
 	$(V)$(GO) run $(GO_MODFLAGS) -tags "$(GO_TAGS)" $(GO_GCFLAGS) $(GO_ASMFLAGS) \
 		$(SOURCEDIR)/cmd/docs/docs.go man --dir $(DESTDIR)$(MANDIR)/man1
 
@@ -17,41 +18,59 @@ collect:
 	done
 
 .PHONY: check
-check: $(go_OBJ)
+check: codegen
 	@echo " CHECK golangci-lint"
-	$(V)cd $(SOURCEDIR) && \
-		(PATH=$(SOURCEDIR)/bin:$$PATH; \
-		 (command -v golangci-lint >/dev/null || \
-		  curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.15.0) && \
-		 golangci-lint run --build-tags "$(GO_TAGS)" ./...)
+	$(V) cd $(SOURCEDIR) && \
+		scripts/run-linter run --verbose --build-tags "$(GO_TAGS)" ./...
 	@echo "       PASS"
 
 .PHONY: dist
 dist:
-	$(V)(cd $(SOURCEDIR) && $(SOURCEDIR)/scripts/make-dist.sh)
+	$(V) if test -e '$(SOURCEDIR)/vendor' ; then \
+		echo 'E: There is a vendor directory in $(SOURCEDIR).' ; \
+		echo 'E: This is unexpected. Abort.' ; \
+		exit 1 ; \
+	fi
+	$(V) cd $(SOURCEDIR) && $(GO) mod vendor
+	$(V) cd $(SOURCEDIR) && $(SOURCEDIR)/scripts/make-dist.sh $(VERSION)
+	$(V) rm -rf '$(SOURCEDIR)/vendor'
 
 .PHONY: unit-test
+unit-test: EXTRA_FLAGS := $(if $(filter yes,$(strip $(JUNIT_OUTPUT))),-junit $(BUILDDIR_ABSPATH)/unit-test.xml)
 unit-test:
 	@echo " TEST sudo go test [unit]"
-	$(V)cd $(SOURCEDIR) && sudo -E $(GO) test $(GO_MODFLAGS) -count=1 -timeout=20m -tags "$(GO_TAGS)" -failfast -cover -race \
-		`$(GO) list ./... | grep -v "cmd/singularity\|pkg/network"`
+	$(V)cd $(SOURCEDIR) && \
+		sudo -E \
+		scripts/go-test -v $(EXTRA_FLAGS) \
+		./...
 	@echo "       PASS"
 
+
+.PHONY: e2e-test
+e2e-test: EXTRA_FLAGS := $(if $(filter yes,$(strip $(JUNIT_OUTPUT))),-junit $(BUILDDIR_ABSPATH)/e2e-test.xml)
+e2e-test:
+	@echo " TEST sudo go test [e2e]"
+	$(V)cd $(SOURCEDIR) && scripts/e2e-test -v $(EXTRA_FLAGS)
+	@echo "       PASS"
 
 .PHONY: integration-test
 integration-test:
 	@echo " TEST sudo go test [integration]"
-	$(V)cd $(SOURCEDIR) && sudo -E $(GO) test $(GO_MODFLAGS) -count=1 -timeout=20m -tags "$(GO_TAGS)" -failfast -cover -race \
+	$(V)cd $(SOURCEDIR) && \
+		sudo -E \
+		scripts/go-test -v -tags 'integration_test' \
 		./cmd/singularity ./pkg/network
 	@echo "       PASS"
-
 
 .PHONY: test
 test:
 	@echo " TEST sudo go test [all]"
 	$(V)M=0; eval 'while [ $$M -le 20 ]; do sleep 60; M=`expr $$M + 1`; echo "Still testing ($$M) ..."; done &' ; \
     	trap "kill $$! || true" 0; \
-		cd $(SOURCEDIR) && sudo -E $(GO) test $(GO_MODFLAGS) -count=1 -timeout=20m -tags "$(GO_TAGS)" -failfast -cover -race ./...
+		cd $(SOURCEDIR) && \
+		sudo -E \
+		scripts/go-test -v -tags 'integration_test' \
+		./...
 	@echo "       PASS"
 
 .PHONY: testall
@@ -67,10 +86,10 @@ rpm: dist
 	      --define '_sysconfdir $(RPMPREFIX)/etc' \
 	      --define '_localstatedir $(RPMPREFIX)/var' \
 	      --define '_mandir $(RPMPREFIX)/share/man' \
-	      $(SOURCEDIR)/singularity-$(SHORT_VERSION).tar.gz; \
+	      $(SOURCEDIR)/singularity-$(VERSION).tar.gz; \
 	  else \
 	    rpmbuild $(RPMCLEAN) -ta \
-	      $(SOURCEDIR)/singularity-$(SHORT_VERSION).tar.gz; \
+	      $(SOURCEDIR)/singularity-$(VERSION).tar.gz; \
 	  fi)
 
 .PHONY: cscope
@@ -82,16 +101,10 @@ cscope:
 .PHONY: clean
 clean:
 	@printf " CLEAN\n"
-	$(V)rm -rf $(BUILDDIR)/mergeddeps cscope.* bin/golangci-lint $(CLEANFILES)
+	$(V)rm -rf $(BUILDDIR)/mergeddeps cscope.* $(CLEANFILES)
 
 .PHONY: install
 install: $(INSTALLFILES)
 	@echo " DONE"
-
-# generate the vendor folder with dep
-.PHONY: vendor
-vendor:
-	@echo " VENDOR"
-	$(V)$(GO) mod vendor >/dev/null
 
 -include $(BUILDDIR)/mergeddeps
